Will print traceback of origin exception in __init__.py